name: Build
on: push

jobs:
    deploy_app:
        name: Deploy Application to Azure
        runs-on: ubuntu-latest

        steps:
        - name: Load Repository
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: 'npm'

        - name: Create local.env for Dockerfile
          run: |
            echo ROOT_SQL_SERVER_USERNAME=${{ secrets.ROOT_SQL_SERVER_USERNAME }} > local.env
            echo ROOT_SQL_SERVER_PASSWORD=${{ secrets.ROOT_SQL_SERVER_PASSWORD }} >> local.env
            echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> local.env
            echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> local.env
            echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> local.env
            echo ACCEPT_EULA=${{ secrets.ACCEPT_EULA }} >> local.env
            echo LIQUIBASE_ADMIN_USERNAME=${{ secrets.LIQUIBASE_ADMIN_USERNAME }} >> local.env
            echo LIQUIBASE_ADMIN_PASSWORD=${{ secrets.LIQUIBASE_ADMIN_PASSWORD }} >> local.env
            echo LIQUIBASE_DEFAULT_SCHEMA=${{ secrets.LIQUIBASE_DEFAULT_SCHEMA }} >> local.env

        - name: Create .env for Web App
          run: |
            echo DB_USER=${{ secrets.DB_USER }} > .env
            echo DB_PASS=${{ secrets.DB_PASS }} >> .env
            echo DB_SERVER=${{ secrets.DB_SERVER }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env

        - name: Build Dockerfile
          run: |
            cd services/containers/database
            docker build --tag 'db_setup' .
            docker run --detach 'db_setup'

        - name: npm install, build, and test
          run: |
            npm install
            npm run build --if-present
            npm run test --if-present

        # - name: Upload artifact for deployment job
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: node-app
        #     path: .

        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v3
          with:
            app-name: wapp-azuredemowebapplication
            publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}